# Introduction to Tensors

In [4]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 2.6478e-15,  4.5740e-41,  2.6478e-15],
        [ 4.5740e-41,  1.3458e-14,  2.8175e+20],
        [ 1.3556e-19,  7.2053e+22,  4.7428e+30],
        [ 1.8580e-19,  1.3567e-19,  8.2990e-33],
        [ 1.3563e-19,  1.3563e-19,  1.3563e-19]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.1754,  0.6089,  0.0641],
        [ 0.7968,  0.4930,  0.6583],
        [ 0.8438,  0.6835,  0.2407],
        [ 0.9737,  0.8593,  0.9660],
        [ 0.3165,  0.9793,  0.6975]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x) 

tensor([[-0.5719, -0.7760, -1.3770],
        [-0.0992, -0.4458,  2.1819],
        [-1.7542,  0.6437,  1.1318],
        [-0.2325,  0.8603, -1.4871],
        [-0.6499, -0.5610, -1.5723]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.0524, -0.3504, -0.6016],
        [ 0.1948,  0.1210,  3.1417],
        [-1.0351,  1.0071,  1.7310],
        [ 0.1391,  1.4524, -1.2219],
        [-0.2811,  0.0286, -1.1370]])


In [10]:
result = torch.empty(5, 3)

In [11]:
torch.add(x, y, out=result) # result should be predefined 

tensor([[ 0.0524, -0.3504, -0.6016],
        [ 0.1948,  0.1210,  3.1417],
        [-1.0351,  1.0071,  1.7310],
        [ 0.1391,  1.4524, -1.2219],
        [-0.2811,  0.0286, -1.1370]])

In [12]:
result

tensor([[ 0.0524, -0.3504, -0.6016],
        [ 0.1948,  0.1210,  3.1417],
        [-1.0351,  1.0071,  1.7310],
        [ 0.1391,  1.4524, -1.2219],
        [-0.2811,  0.0286, -1.1370]])

In [13]:
y.add_(x)

tensor([[ 0.0524, -0.3504, -0.6016],
        [ 0.1948,  0.1210,  3.1417],
        [-1.0351,  1.0071,  1.7310],
        [ 0.1391,  1.4524, -1.2219],
        [-0.2811,  0.0286, -1.1370]])

### Any operation that mutates a tensor in-place is post-fixed with an underscore. For example: x.copy_(y), x.t_(), will change x.

In [14]:
x

tensor([[-0.5719, -0.7760, -1.3770],
        [-0.0992, -0.4458,  2.1819],
        [-1.7542,  0.6437,  1.1318],
        [-0.2325,  0.8603, -1.4871],
        [-0.6499, -0.5610, -1.5723]])

In [15]:
x[:,0]

tensor([-0.5719, -0.0992, -1.7542, -0.2325, -0.6499])

### The last arg is the column

In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

In [17]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### view converts one Tensor into another. -1 means infer the dimension automatically.

In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.5994])
-1.5993603467941284


In [19]:
b = z.numpy()

In [20]:
b

array([[ 0.31775513, -1.15440726, -0.06971171,  0.14034157, -1.06520784,
         0.99834687,  1.06390595, -0.52552944],
       [-0.5493865 , -0.35949713,  0.17272897,  1.13955271, -0.36486673,
         0.66864628, -0.51446414, -1.69722402]], dtype=float32)

In [5]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [22]:
torch.cuda.is_available()

True

In [23]:
y = torch.ones_like(x, device=torch.device("cuda"))

In [24]:
x

tensor([-1.5994])

In [25]:
x = x.to(torch.device("cuda"))

In [26]:
x

tensor([-1.5994], device='cuda:0')

### This allows us to create a tensor on GPU or to move a tensor to GPU using .to(device)

In [27]:
z = x + y

In [28]:
z

tensor([-0.5994], device='cuda:0')

In [29]:
 print(z.to("cpu")) 

tensor([-0.5994])


In [30]:
 print(z.to("cpu", torch.double)) 

tensor([-0.5994], dtype=torch.float64)


# Autograd

`torch.Tensor` is the central class of the package. If you set its attribute `.requires_grad` as `True`, it starts to track all operations on it. When you finish your computation you can call `.backward()` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into `.grad` attribute.

In [31]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [32]:
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [33]:
print(y.grad_fn)

In [34]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [35]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [36]:
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

True


In [37]:
out.backward()

In [38]:
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [39]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:  # Check with 2-Norm of matrix (Root of largest Eigen value of A'A)
    y = y * 2

print(y)

tensor([  -8.7454,  982.8367,  333.2024])


In [40]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([  51.2000,  512.0000,    0.0512])


In [41]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():   # In a torch.no_grad block, requires_grad is ignored.
    print((x ** 2).requires_grad)

True
True
False


# Neural Nets

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [9]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 5, 5])


## torch.nn only supports mini-batches. The entire torch.nn package only supports inputs that are a mini-batch of samples, and not a single sample.

### For example, nn.Conv2d will take in a 4D Tensor of nSamples x nChannels x Height x Width.

### If you have a single sample, just use input.unsqueeze(0) to add a fake batch dimension.

In [10]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)
output = net(input)
target = torch.arange(1, 11)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor([[-0.0591,  0.0332, -0.0441, -0.0794, -0.0185, -0.0618,  0.0084,
          0.0085, -0.0294, -0.1983]])
tensor(39.1112)


In [11]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [ ]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()  